# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Elixir.gitlab-ci.yml

# also setup the coverage
cache:
  key:
    files:
      - mix.lock
  untracked: true
  paths:
    - _build/
    - deps/

stages:
  - build
  - test
  - deploy
  - smoke

.elixir:
  image: elixir:1.13.4
  # Pick zero or more services to be used on all builds.
  # Only needed when using a docker container to run your tests in.
  # Check out: https://docs.gitlab.com/ee/ci/services/index.html
  services:
  #  - mysql:latest
  #  - redis:latest
    - postgres:latest

  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV

  variables:
    GIT_SUBMODULE_STRATEGY: normal
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: postgres

print-vars:
  stage: build
  script:
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_BRANCH

lint-job:
  extends: .elixir
  stage: build
  variables:
    MIX_ENV: dev
  allow_failure: false
  script:
    - mix compile --warnings-as-errors --force
    - mix format --check-formatted
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "nevergoingtorun"
    
test-job:
  extends: .elixir
  stage: test
  variables: 
    MIX_ENV: test

  coverage: '/\d+.\d+\%\s+\|\s+Total/'
  script:
    #- mix test --color apps/fubars/test/
    #- mix test --color apps/frobots/test/
    #- mix test --color apps/frobots_web/test/
    - mix coveralls --umbrella || true
    - mix test
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "eouoeu"
  artifacts:
    paths:
      - _build/test/lib/frobots/test-junit-report.xml
      #- _build/test/lib/frobots_web/test-junit-report.xml
      #- _build/test/lib/fubars/test-junit-report.xml
      
    reports:
      junit: _build/test/lib/frobots/test-junit-report.xml
      #junit: _build/test/lib/frobots_web/test-junit-report.xml
      #junit: _build/test/lib/fubars/test-junit-report.xml 

deploy-job:
  image: elixir:latest
  stage: deploy
  variables:
    POOL_SIZE: 2
    PORT: 4000
    GIT_SUBMODULE_STRATEGY: normal
    
  before_script:
    - (cd $(mktemp -d) && wget https://download.docker.com/linux/static/stable/x86_64/docker-20.10.9.tgz && tar xvzf * && cp docker/* /usr/local/bin/ && chmod +x /usr/local/bin/*)
  
  script:
    - ./contrib/build.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

server-test:
  stage: smoke
  needs: ["deploy-job"]
  script:
    - ./contrib/test_server.sh https://internal.frobots.io "Welcome to FROBOTS BETA"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
 
