# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Elixir.gitlab-ci.yml

stages:
  - test
  - deploy

.elixir: &elixir
  image: elixir:latest
  # Pick zero or more services to be used on all builds.
  # Only needed when using a docker container to run your tests in.
  # Check out: https://docs.gitlab.com/ee/ci/services/index.html
  services:
  #  - mysql:latest
  #  - redis:latest
    - postgres:latest

  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only $MIX_ENV

  variables:
    POSTGRES_DB: frobots_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    GIT_SUBMODULE_STRATEGY: normal
    POSTGRES_HOST: postgres
    TERM: xterm-256color

lint:elixir:
  extends: .elixir
  stage: test
  variables:
    MIX_ENV: test
  allow_failure: true
  script:
    - mix compile --warnings-as-errors --force
    - mix format --check-formatted
    
test-job:
  extends: .elixir
  stage: test
  variables: 
    MIX_ENV: test
  script:
    - mix test apps/fubars/test/
    - mix test apps/frobots/test/
    - mix test apps/frobots_web/test/
  rules:
    - if: $CI_COMMIT_BRANCH == "nevergoingtorun"

deploy-job:
  extends: .elixir
  stage: deploy
  variables:
    POOL_SIZE: 2
    PORT: 4000
    SECRET_KEY_BASE: $(mix phx.gen.secret)

  script:
    - mix release
    - ./contrib/build.sh