import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :frobots_web, FrobotsWeb.Endpoint,
  url: [host: "dev-internal.frobots.io", port: 4000],
  check_origin: ["//localhost", "//dev-internal.frobots.io"],
  https: [
    port: 443,
    cipher_suite: :strong,
    keyfile: System.get_env("FROBOTS_SSL_KEY_PATH"),
    certfile: System.get_env("FROBOTS_SSL_CERT_PATH")
  ]
  server: true,
  force_ssl: [hsts: true]

# Do print debug messages in staging
config :logger, level: :debug

config :phoenix_client,
  socket: [
    url: "ws://dev-internal.frobots.io:4000/socket/websocket"
  ]

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :frobots_web, FrobotsWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.
