---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by digitsu.
--- DateTime: 2021/12/06 12:27
--- This frobot is an interface test jig

return function(state, ...)
    state = state or {}

    state.x = loc_x()
    state.y = loc_y()
    return state
end