---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by digitsu.
--- DateTime: 2021/12/06 12:27
--- This frobot is an interface test jig
---
--- dummy frobot sits there until damaged, when he will run away in a random direction at half speed, until he hits an obstacle

return function(state, ...)
    state = state or {}
    state.type = "dummy"
    if state.damage == nil or state.damage ~= damage() then
        state.damage = damage()
        state.course = math.random(359)
        drive(state.course, 50)
    end

    return state
end