---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by digitsu.
--- DateTime: 2021/12/01 11:28
---

--- rabbit
--- rabbit runs aronud the field randomly
--- and never fires anything, just a moving target

return function(state, ...)
    state = state or {}
    assert(
            type(state) == 'table',
            'Invalid state. Must receive a table'
    )
    math.randomseed( os.time() )
    math.random(); math.random(); math.random()

    local function distance(x1,y1,x2,y2)
        local x = x1 -x2
        local y = y1 -y2
        local d = math.sqrt((x*x) + (y*y))
        return d
    end

    local function plot_course(xx,yy)
        local d
        local curx = loc_x()
        local cury = loc_y()
        local x = xx - curx
        local y = yy - cury

        if x == 0 then
            if yy > cury then
                d = 90.0
            else
                d = 270.0
            end
        else
            d = math.atan(y, x) * 180/math.pi
        end
        return d
    end

    if state.dest == nil or state.dest == false then
        state.dest = {math.random(1000), math.random(1000)} --- go somewhere in the grid
        state.course = plot_course(state.dest[1], state.dest[2])
        drive( state.course, 100)
    end

    if distance(loc_x(), loc_y(), state.dest[1], state.dest[2]) < 50 then
        drive(state.course, 0)
        state.course = 0
        state.dest = false
        cannon(math.random(350), math.random(700))
    end
    drive(state.course, 100)

    return state
end