---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by digitsu.
--- DateTime: 2021/12/01 11:28
---

--- rabbit
--- rabbit runs aronud the field randomly
--- and never fires anything, just a moving target

return function(state, ...)
    state = state or {}
    assert(
            type(state) == 'table',
            'Invalid state. Must receive a table'
    )

    --local function sleep(n)
    --    os.execute("sleep " .. tonumber(n))
    --end

    local function distance(x1,y1,x2,y2)
        local x = x1 -x2
        local y = y1 -y2
        local d = math.sqrt((x*x) + (y*y))
        return d
    end

    local function plot_course(xx,yy)
        local d
        local x,y
        local curx, cury


        curx = loc_x()
        cury = loc_y()
        x = curx - xx
        y = cury - yy

        if x == 0 then
            if yy > cury then
                d = 90
            else
                d = 270
            end
        else
            if yy < cury then
                if xx > curx then
                    d = 360 + math.atan(y, x)
                else
                    d = 180 + math.atan(y, x)
                end
            else
                if xx > curx then
                    d = math.atan(y, x)
                else
                    d = 180 + math.atan(y, x)
                end
            end
        end
        return d
    end

    local function go(dest_x, dest_y)
        local course = plot_course(dest_x, dest_y) --- heading
        drive(course,25);
        while distance(loc_x(), loc_y(), dest_x, dest_y) > 50 do
            x = true
        end
        drive(course, 0) -- stop
        while (speed() > 0) do
            x = true
        end
    end

    while true do
        go(math.random(1000), math.random(1000)) --- go somewhere in the grid
    end

    return state
end